### ISSUE TITLE
Suggestion: Add better discord output config

### ISSUE THREAD

**Issue by Joyfulasteroid** [Jarva/VelocityCarbonDiscord#6]
Currently the best way to format messages is using the webhook as it shows the user and the message. 

It would be great if you could configure it so the output has the option to add the server the message originated from or set the username to be different (like showing their luckperms prefix) without it affecting the output of the message in game

**Comment by unilock** [comment]
VelocityCarbonDiscord is compatible with all placeholders from [MiniPlaceholders](https://modrinth.com/plugin/miniplaceholders) and its extensions, including [Player Expansion](https://modrinth.com/plugin/player-expansion) for the player's current server and [LuckPerms Expansion](https://modrinth.com/plugin/luckperms-expansion) for their LuckPerms prefix. Simply install all plugins alongside one another and use the placeholders they provide in VelocityCarbonDiscord's config.

**Comment by Joyfulasteroid** [comment]
The issue is you have to change the username with the placeholders and not the message it sends. IF you edit the message then for some reason the message edited for discord is what is sent in game. 

The way round it is to use webhooks and change the name. However this didn't achieve the look I wanted and so I moved on to a different setup with other plugins

**Comment by unilock** [comment]
You have to use the placeholders in VelocityCarbonDiscord's config, not Carbon's config. Unless I'm misunderstanding the problem?

**Comment by Joyfulasteroid** [comment]
The problem isnt the availability of placeholder. THe issue is that editing the message that gets sent to discord edits the message that also gets seen in game

**Comment by unilock** [comment]
What config value are you editing to change the message sent to Discord?

It should be either this value in `velocitycarbondiscord/config.yml`:

<img width="581" alt="image" src="https://github.com/Jarva/VelocityCarbonDiscord/assets/11802133/95913741-3d87-40f7-a217-9f2e4738e5fa">

...or this value in the same file, if you're using a webhook:

<img width="507" alt="image" src="https://github.com/Jarva/VelocityCarbonDiscord/assets/11802133/85769bbf-d234-464d-9ec9-cc9c6446fc9f">
